<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS -->
    <link href="https://fonts.googleapis.com/css?family=BenchNine|Economica|Open+Sans+Condensed:300|Wire+One|Quicksand:300" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/stylehome.css" />
    <!-- Jquery -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous"></script>

    <title>Maxime Dolo</title>

</head>
<body id="body-about">

    <!-- HEADER -->
    <?php
        include("headerabout.php");
     ?>
   <!-- HEADER -->

   <!-- MAIN CONTENT -->
    <main class="main_about">

        <article class="article-about">
            <h3><u>À propos de moi</u></h3>
            <p>Après un baccalauréat STI Arts Appliqués, j'ai suivi une formation de quatre années à l'Ecole Pivaut de Nantes en section Graphisme publicitaire (aujourd'hui appelée Design graphique).</p>
            <p>A la suite de mon diplôme, j'ai travaillé durant plus de deux ans dans le print Packaging, en tant que graphiste au sein d'une agence de Flexographie.</p>
            <p>Attiré par le Web et les nouvelles technologies depuis longtemps, c'est en 2017 que j'ai décidé de suivre une formation de Développeur-Intégrateur Web au sein de la 3WA.</p>
        </article>

        <section class="section-skills">
            <h3><u>Mes Compétences</u></h3>
                <article class="article-skills">
                    <h4><i class="fa fa-pencil" aria-hidden="true"></i> Design</h4>
                    <ul>
                        <li><img src="images/icons/icon_ps.jpg" alt="Photoshop"><p>Photoshop</p></li>
                        <li><img src="images/icons/icon_ai.jpg" alt="Illustrator"><p>Illustrator</p></li>
                        <li><img src="images/icons/icon_id.jpg" alt="Indesign"><p>Indesign</p></li>
                        <li><img src="images/icons/icon_fl.jpg" alt="Flash"><p>Flash</p></li>
                        <li><img src="images/icons/icon_pr.jpg" alt="Premiere"><p>Premiere</p></li>
                    </ul>
                </article>

                <article class="article-skills">
                    <h4><i class="fa fa-eye" aria-hidden="true"></i> Développement Front-End</h4>
                    <ul>
                        <li><img src="images/icons/icon_js.png" alt="Javascript"><p>Javascript</p></li>
                        <li><img src="images/icons/icon_jq.png" alt="jQuery"><p>jQuery</p></li>
                    </ul>
                </article>

                <article class="article-skills">
                    <h4><i class="fa fa-code" aria-hidden="true"></i> Intégration</h4>
                    <ul>
                        <li><img src="images/icons/icon_html.png" alt="Html"><p>HTML5</p></li>
                        <li><img src="images/icons/icon_css.png" alt="Css"><p>Css3 &</p><p>Responsive</p></li>
                        <li><img src="images/icons/icon_bo.jpg" alt="Bootstrap"><p>Bootstrap</p></li>
                    </ul>
                </article>

                <article class="article-skills">
                    <h4><i class="fa fa-cogs" aria-hidden="true"></i> Développement Back-End</h4>
                    <ul>
                        <li><img src="images/icons/icon_php.jpg" alt="Php"><p>PhP</p><p>POO/MVC</p></li>
                        <li><img src="images/icons/icon_si.png" alt="Silex"><p>Silex</p></li>
                        <li><img src="images/icons/icon_sql.png" alt="Mysql"><p>MySQL</p></li>
                    </ul>
                </article>

        </section>

    </main>
   <!-- MAIN CONTENT -->

   <!-- FOOTER -->

    <?php
        include("footer.php");
     ?>

   <!-- FOOTER -->

</body>
</html>
