<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
    <link href="https://fonts.googleapis.com/css?family=BenchNine|Economica|Open+Sans+Condensed:300|Wire+One|Quicksand:300" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/stylehome.css" />
    <link rel="stylesheet" type="text/css" href="css/popupstyle.css" />
    <!-- Jquery -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous"></script>

    <title>Maxime Dolo</title>

</head>
<body>

    <!-- HEADER -->
    <?php
        include("headersection.php");
     ?>
   <!-- HEADER -->

   <!-- MAIN CONTENT -->
    <main>

        <section class="album">
            <?php
            foreach($travaux as $miniatMenu) :
            ?>
                <figure class="vignette" data-index="<?= $miniatMenu["idTravaux"]; ?>">
                    <img class="imagevignette" src="<?= $miniatMenu["miniature"]; ?>" alt="rough"/>
                    <figcaption class="textevignette"><?= $miniatMenu["titre"]; ?><br>
                        <?= $miniatMenu["techniques"]; ?><br>
                        <?= $miniatMenu["dateCrea"]; ?>
                    </figcaption>
                </figure>


            <?php
            endforeach
            ?>
        </section>

        <!-- JAVASCRIPT ModalSlider-->
        <!-- The Modal -->

        <section id="myModal" class="modal">
            <p>...</p>
        </section>

    </main>
   <!-- MAIN CONTENT -->

   <!-- FOOTER -->
    <?php
        include("footer.php");
     ?>
   <!-- FOOTER -->
   <script src="js/mainCategory.js"></script>

</body>
</html>
