<section id="contactPopUp" class="modal">

    <div class="modal-content">
        <!-- HEADER -->
        <div class="modal-header">
            <span class="close">&times;</span>
            <h2>Contactez-moi!</h2> <!-- titre -->
        </div>

        <!-- BODY-->
        <div class="modal-body">

            <p><i class="fa fa-at" aria-hidden="true"></i> Mail : <a href="mailto:maximedolo@gmail.com?subject=feedback">maximedolo@gmail.com</a></p>
            <p><i class="fa fa-phone" aria-hidden="true"></i> Tel : <strong>06.75.15.79.39</strong></p>
            <p><i class="fa fa-user" aria-hidden="true"></i></i> LinkedIn : <a href="https://www.linkedin.com/in/maxime-dolo-0b087a12b">Maxime Dolo</a></p>


        </div><!--
        --><div class="modal-footer"></div>
    </div>

</section>
